[wasm_modules]
# @Note we need to manually include the wasm modules used for Cloudflare workers
# These modules will be injected as global vars into the worker
JPEG_DEC_WASM = "node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm"
PNG_DEC_WASM = "node_modules/@jsquash/png/codec/squoosh_png_bg.wasm"
WEBP_ENC_WASM = "node_modules/@jsquash/webp/codec/enc/webp_enc_simd.wasm"
RESIZE_WASM = "node_modules/@jsquash/resize/lib/resize/squoosh_resize_bg.wasm"
